repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sorting imports
        args: [
            "--profile=black",
          ]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: Black formatting

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.166
    hooks:
      - id: ruff
        name: Ruff linting

  - repo: local
    hooks:
      - id: pytest-check
        name: Running pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
